### ISSUE TITLE
When building with clang on windows, there are 36k lines of warnings and the build fails

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#100]
https://ci.appveyor.com/project/RPGHacker/asar/build/247/job/hpgecqcxbrtu2umh
I was unable to figure out why it fails, but most of the warnings look like really minor things that should be ignored. I don't understand how this didn't happen on the appveyor-gcc-tests branch though.

**Comment by RPGHacker** [comment]
That's what I'm wondering too, huh. Maybe some minor change on master that somehow completely messed it up after merging. Or something in the later commits (the ones with [skip appveyor]) that somehow broke it, though I don't think that's very likely.

**Comment by randomdude999** [comment]
I checked, the skip appveyor commits only modify .travis.yml which can't affect appveyor. What's really weird is that I didn't find a single error from the (3 MB) build log.

**Comment by RPGHacker** [comment]
Yeah, it kinda looks like the log is incomplete. Maybe the build was interrupted somehow...

**Comment by RPGHacker** [comment]
I've just went through the trouble of building and installing LLVM on my system, and ironically, I do not get any of those warnings when I build Asar against LLVM-vs2014. I did get a couple of legitimate warnings (maybe around 20 or so), and I'm getting hundreds of warnings like this
```
ignoring unknown option '-fms-extensions'
```
However, not getting most of the warnings from that gigantic build log.

**Comment by RPGHacker** [comment]
(The build also succeeds on my machine)

**Comment by randomdude999** [comment]
It is very odd. Even the last commit on the appveyor-gcc-tests branch didn't have those warnings. At least it didn't until you accidentally commited the changelog update there, at which point even that errored. However, the last commit that was built on appveyor (b03bdcde4d6aa87b40d56837d1a70fdfc7586d0c) didn't error, and the only things between that and the new build have been updates to .travis.yml. I am suspecting the Appveyor team updating their Clang image and enabling some extra warnings by default.

**Comment by randomdude999** [comment]
That is indeed the case. On the 16th of May (3 days after my commits), Appveyor did a [rather large update](https://www.appveyor.com/updates/2018/05/16/). In there, they upgraded to LLVM 6.0. Try seeing if those warnings are present on LLVM 6.0 on your machine.

**Comment by RPGHacker** [comment]
Well, LLVM 6.0.0 is apparently the version I installed, so... :/

http://releases.llvm.org/download.html

The first archive on that website was the one I downloaded and built.

**Comment by RPGHacker** [comment]
(I did built LLVM as a 64-bit version, but I can't imagine that making that much of a difference)

**Comment by RPGHacker** [comment]
Also that website has an installer, apparently. How did I not see that before? Typical me moment. Wasted a couple of hours for nothing.

**Comment by RPGHacker** [comment]
Yup. Now getting those warnings and errors, too, after using the installer. Don't ask me how the source and installer are different, I have no idea.

**Comment by randomdude999** [comment]
As weird as it may sound, i think that msbuild is, for some reason, interpreting the "Internal error : a label is moving around" in the output (it is there because there's a warning on that line) as an actual error and breaking the build.

**Comment by randomdude999** [comment]
Also, ~3k of the ~6k warnings I get are from -Wold-style-cast, and ~0.5k are from -Wc++98-compat.

**Comment by RPGHacker** [comment]
That's very possible. As far as I know, MSBuild basically just looks at the output of the compiler and interprets everything starting with `error :` as an error, so it may just be derpy there.

And yeah, currently looking how to disable -Wold-style-casts for MSVC-LLVM. Don't really want to use static_cast everywhere, so I would rather disable it for Asar.

**Comment by RPGHacker** [comment]
So yeah, cleaning up the code actually took a whoooooole lot of effort. I mean, fixing the errors would have been simple enough, it weren't that many, but most of the warnings were worth taking a look at, because getting all those warnings was pretty much my sole point of wanting a Clang build in the first base. As a result, I think the code got a whole lot cleaner, although in a few places also slightly hackier. Some warnings had to be disabled, because while legit, I don't think they're reasonably fixable in Asar without investing a huge amount of time.

Interestingly enough, the v141_clang_c2 build broke for me, but I'm not quite sure why. One of the reasons is specifying /EHa on the command line, which that version of Clang doesn't understand, but even if I take it out, I get hundreds of errors and a message, that some headers expect Clang version >= 6. Not sure why that wasn't an issue before, though. Probably something a recent VS2017 update caused. Since LLVM-vs2014 is working now and provides way more warnings than v141_clang_c2 ever did, I don't really care, though.

**Comment by RPGHacker** [comment]
And closing, since the build now succeeds again.
