### ISSUE TITLE
Add address-to-line mapping and source file list to WLA Symbols file

### ISSUE THREAD

**Issue by CypherSignal** [RPGHacker/asar#124]
Recently, I submitted the following PR for wla-dx: https://github.com/vhelin/wla-dx/pull/202

Most notably, it adds extra information into WLA's Symbols file, such as a mapping of ROM addresses to source files and line numbers. In the PR, it is demonstrated how this information is used, including allowing VS Code to act as a moderately capable IDE for patch development, allowing for stuff like interactive breakpoints flagged in the editor, and reporting callstacks that refer to source files.

![VSCode displaying breakpoints, current PC, and callstack](https://i.imgur.com/4xFTpF9.png)

Given how much asar is used in the homebrew community for ROM and patch development, I wanted to look into developing similar support here, as well. I'm a bit unfamiliar with Asar and how it operates, but with a quick glance, it seems that support would be more involved than the changes needed for wla-dx and, hence, may be a greater burden to maintain in the long run (e.g. wla-dx already had a lot of support for mapping ROM addresses to source text by way of its List file output). Because of this, I want to, in particular, seek permission from the maintainers to develop this feature, or even, perhaps, advice on how it would be preferable to develop it.

So, would there be any thoughts or comments on inclusion of such a feature?

**Comment by randomdude999** [comment]
A rom-address-to-source-line mapping is actually pretty simple - all the ROM writes should already go through a write1 function which can be hooked into, and i'm pretty sure the current line number is stored in a global somewhere (for error reporting). However, this approach would probably give every byte of the written area separately (i.e. `LDA #$64` will result in 2 different entries), which would make the list file absolutely massive. A smarter approach would probably be to use the existing written block tracking to figure out the blocks written in each line, maybe at the end of `assembleline`.

**Comment by RPGHacker** [comment]
(Partially ninja'd by randomdude999, but here goes my reply, anyways)

Regarding permission: sure, feel free to go ahead. Don't think any of us could really prohibit this, anyways, since Asar's license permits modifying the source code for most purposes. It's also a very useful feature, so if you end up with a working solution and make a pull request, it's very likely we'll merge it into this repository (although it might take a while, because activity on Asar development is currently pretty low and likely won't change for at least a couple of months).

As for suggestions: difficult to say, really. Asar is, in many regards, a pretty hacky job. The source code, for the most part, isn't well structured or easily readable, nor is stuff in consistent locations. This alone will likely make implementing this a bit tricky. On the plus side, though: if you do end up with a working solution and this solution happens to be a "dirty" or "hacky" one, it's unlikely that anyone will mind, because Asar is already in that state to begin with.

Now I'm not sure what exactly is all needed to make such a feature work. I assume that, at the most basic level, you need some kind of "source line" to "ROM output location" mapping? If so, a good place to start would probably be the function `assemblefile()`, which iterates over all lines in a file and then calls another function to generate their output. There will likely be a few hurdles along the way, though. For example: macros could be a bit tricky to deal with, assuming you want to support them. I guess most of the complexity here really comes down to how verbose you want to make the mapping and how capable the debuggers are that support this feature.

**Comment by CypherSignal** [comment]
Okay, thanks for the responses, both. This will help with some early orientation for this problem.

>Don't think any of us could really prohibit this, anyways, since Asar's license permits modifying the source code for most purposes

Well sure, but there's a difference between telling other developers, "Just grab the normal main Asar release at v 1-point-whatever" and "Compile this other person's fork of Asar for this one feature, and it might occasionally be up-to-date", y'know? :) 

>I assume that, at the most basic level, you need some kind of "source line" to "ROM output location" mapping?

Yeah, that's the biggest piece of the puzzle. That, plus knowledge of what every included file is, and then running checksums on everything. Regarding macros, I say the expected output should be that the source-line of every instruction contained in a macro should be that of where the macro was used.
