### ISSUE TITLE
Unable to include Asar in a project with Unicode support

### ISSUE THREAD

**Issue by MarioFanGamer** [RPGHacker/asar#163]
This is a Windows issue: `getlib()` on Windows in asardll.c is defined as `LoadLibrary("asar.dll")`. The problem is that this function returns a wchar_t if Unicode is activated which prevents the program to find Asar. It only works if Unicode is disabled.

**Comment by RPGHacker** [comment]
Ah, yeah, good catch.

Luckily, should be easy to fix by doing either

``´LoadLibrary(_T("asar.dll"))```

or (my preferred solution)

``´LoadLibraryW(L"asar.dll")``´

**Comment by Alcaro** [comment]
My favorite would be changing every LoadLibrary to LoadLibraryA, so asar_init_with_dll_path won't need a bunch of weird tricks.

Also, because [utf16 fucking sucks](http://utf8everywhere.org/).

**Comment by RPGHacker** [comment]
UTF-16 does suck, but currently it's also unfortunately the only reliable way to support Unicode file paths reliably on Windows. Of course there are experimental changes to Windows that enable UTF-8 support, but those will never be available for everyone.

Not that this really matters for this hard-coded path where we just pass "asar.dll" directly, but for paths where a user-specified string can be used, it does matter, even though just a low percentage of users will ever be affected by it. I did fix way too many "ANSI function was used in the Windows version" problems in the past to know that there will always be the rare case where people do put their stuff into a non-ANSI directory, though.

I'd say most commonly this happens with someone's Documents directory. Since that just resides in the user directory on Windows - which can be named anything - putting anything asar.dll related in there could easily trigger the bug, at least for tools using an absolute path (which, in my opinion, should always be done as a best practice). So it would be as simple as someone with a non-ANSI system putting all their ROM-hacking related stuff into their Documents directory for there to be a realistic chance of breaking.

**Comment by Alcaro** [comment]
Yes, it's irrelevant for "asar.dll", but it matters for asar_init_with_dll_path. You'll need to decide what charset that one uses.

If UTF-8, someone's gonna send a local codepage string, they're more easily available.
If local codepage, you may encounter unrepresentable characters (and someone's probably gonna use UTF-8 anyways because the entire concept of codepages is insane).
If UTF-16, callers will need a bunch of #ifdef _WIN32 on their data types (or use UTF-16 on Linux, which is even worse).
Or you could just delete the entire function and tell people to put asar.dll beside the .exe.

I don't know which answer is the least bad.

(My personal favorite is patching a pile of system DLLs in memory and replace the codepage-to-utf16 function with utf8, but that solution has its own drawbacks. To start with, libraries like Asar have no right to mess with process-global state like that.)

**Comment by RPGHacker** [comment]
Yeah, tricky indeed. My usual way to go about this is to use UTF-8 everywhere and then only convert to UTF-16 in the backend whenever calling a Windows function (better general Unicode support is on the current to-do list for Asar, anyways - currently it doesn't even use UTF-8 anywhere, AFAIK). People who use the binding should have the headers, so the expected encoding cut be put into a comment in the header.

Of course the problem with that is that there would likely be cases where people either overlooked or disregarded that comment, so Asar should have some way of generating an error when receiving a string with a broken encoding. Or rather the Asar binding, in this case. That could indeed make it a bit ugly, because if I remember correctly, the binding is currently mostly isolated from the rest of the code base (for good reasons), so it would likely need its own set of functions for verifying/converting strings. Not a plreasent thought. It would be easier if the problem was only within Asar itself, as that already uses its own string class in most places.

**Comment by RPGHacker** [comment]
Added a fix for this in fc023f4c048fbb2699dffe1e87223434e4be3467, because someone needed it for their application. I ended up going the quick and dirty route and using MultiByteToWideChar() for UTF-8 -> UTF-16 conversion directly in asardll.c. Not necessarily my favorite solution, but I wanted to get it done quickly and it works, so there's that.
