### ISSUE TITLE
Bank byte shorthand

### ISSUE THREAD

**Issue by p4plus2** [RPGHacker/asar#172]
I propose adding a shorthand for accessing bank bytes when loading label constants.  My current suggestion is the following syntax: `lda #<:mylabel`

The reason for this syntax is that `:` is the natural bank separator on the SNES and `<` implies a direction "the left".

Adding this is actually a pretty straight forward patch with `prefix("<:", (int)val>>16);` being added to getnum.  This also means that crazy things like `lda #<:mylabel-<:mylabel` are valid.  Open to alternate syntax ideas of course, but I think this one is a fairly natural choice.

Supporting `<:`, `_:`, and `>:` for example (upper, mid, low) could all be possible too.  Not sure if I find the latter two all that practical though.

**Comment by p4plus2** [comment]
Also, just to clarify, the above syntax is compatible with macro parameters still.

**Comment by RPGHacker** [comment]
I think the idea in general of adding syntactic sugar for this situation is a solid one, since code like
`lda.b #mylabel>>16`
is pretty common, yet not pretty looking.

Not sure if I'm a fan of the proposed syntax itself, though. <: is a syntax that I haven't seen in other programming langauges, so it definitely would be something new we'd have to get used to just for Asar. Plus, this might just be a very personal thing, but I find code to get somewhat difficult to parse with my brain once there's too many symbols in it. For example, in your code above, my brain kinda combines the -< part instead of the <: part, which looks similar to a -> which is already used in Asar as well as other programming languages. Maybe not as common in Asar, but still somethign that I think isn't very intuitive.

Alternative idea for the syntax: I think something that might work well and be more intuitive would be to add special variations of the .b/.w/.l specifiers (what are those called again?) for this very purpose. For example, instead of
`lda.b #mylabel>>16`
we could have a
`lda.b16 #mylabel`
with lda.b already being a well-known opcode, and 16 simply being a number (so we wouldn't have to memorize anything new), and the meaning of this would simply be "lda.b, but left shift by 16". Similarly, we could then use the same syntax for something like
`lda.w8 #mylabel'
Okay, admittedly not quite as useful as the first one, but it's something that could be done at no extra cost and wouldn't require yet a new symbol.

I haven't checked if this syntax would be possible, but currently can't think of anything that might be problematic.

**Comment by p4plus2** [comment]
The problem with your proposed syntax is that it only acts as a global opcode shift and isn't able to used as a part of math expressions.  This means you can't use it in defines for example.  In order to keep all math working the syntax needs to be a prefix to the number itself.

**Comment by RPGHacker** [comment]
That's definitely true. Can't think of a proper solution that works on general math while also not requiring a couple of new symbols. Don't know how common that use case is, but yeah, it wouldn't work.

An alternate idea for that would be to add a couple of built-in functions. Something like b8(), b16(), w8() etc. Then we could do:
`lda.b #b16(mylabel)`
Though whether this is actually any more readable than >>16 is up for debate.
An alternative idea would be to have named functions. For example, a bank() function that pretty much just does >>16, used like this
`lda.b #bank(mylabel)`
This would be longer than to just write >>16, so I don't know if there's any interest, but I at least consider it more readable and intuitive, because at least bank() carries a meaning that is easy to grasp from its name alone and also easy to memorize.

So yeah, none of these really satisfying solutions. My only alternative idea would be to add something like swizzling in shader programming languages. Example:
`lda.b mylabel.bank`
However, I'm pretty sure this would conflict with our struct syntax. It might be a solvable problem (because labels are, after all, differeimt from structs), but I don't remember how everything is coded in Asar, so by default, I'll assume it would be tricky to do.

**Comment by p4plus2** [comment]
So something to keep in mind, whatever the chosen syntax shouldn't force 8 or 16 bit specific modes.  As, for example, in my homebrew I'll still use 16 bit access often when I want the bank (either because I'll overwrite the other byte or its unused).  Personally, I prefer a syntactical sugar over a function only because a user can define their own functions if they truly dislike the syntax.  Alternatively, providing the builtins and syntax can be done.  Just a note: while a `.bank` syntax isn't strictly impossible it will have corner cases, I have used `.bank` as a label inside of a struct plenty of times. Also, internally structs are completely resolved as labels as that was their intended use.  That could possibly be changed to make this syntax work though.

I tested out this code in a small block of code in my homebrew to see what it would feel like:
```
	lda #<:titlescreen_palette
	ldx #titlescreen_palette
	jsr dma_full_palette
```

Some alternatives:
```
	lda #:titlescreen_palette
	ldx #titlescreen_palette
	jsr dma_full_palette
```
```
	lda #@titlescreen_palette
	ldx #titlescreen_palette
	jsr dma_full_palette
```

Below I *think* work but haven't fully tested:
```
	lda #bank@titlescreen_palette
	ldx #titlescreen_palette
	jsr dma_full_palette
```

```
	lda #bank::titlescreen_palette
	ldx #titlescreen_palette
	jsr dma_full_palette
```

Not sure how I'd implement these ones but would probably be resolvable:
```
	lda #titlescreen_palette::bank
	ldx #titlescreen_palette
	jsr dma_full_palette
```

```
	lda #{titlescreen_palette}
	ldx #titlescreen_palette
	jsr dma_full_palette
```

(official nintendo method?)
```
	lda #BANK titlescreen_palette
	ldx #titlescreen_palette
	jsr dma_full_palette
```

Some of those are worse than others, but tossed them out there in case it gives other ideas.  syntaxes in the first two groups are trivial to implement, the latter would require a new parsing mechanism and significantly more testing.  I am a bit more of a fan of the shorter syntaxes, otherwise it doesn't really add much over `>>16`.

**Comment by RPGHacker** [comment]
> I am a bit more of a fan of the shorter syntaxes, otherwise it doesn't really add much over >>16.
Well, personally I'm of the opinion that introducing new stuff to save just two or three characters isn't really worth it, anyways. While the case we're discussing here is a commone one, I'd say it's not so common that saving any amount of characters here would be worth it. This means for me personally, adding something new for this would only be worth it if it were more readable and more intuitive. Saving characters isn't a concern to me personally at least.

That being said, from the list of suggestions, I'd say my favorite suggestion so far is
`lda #titlescreen_palette::bank`
because that's pretty readable while also being a construct known from other languages (mainly C++). I'd probably even remove the double colon and make it just
`lda #titlescreen_palette:bank`
which is a construct used in Lua (although it's used for methods there). Though I guess this version would be tricky to parse as a single : is currently used as a separator character.

Man, adding anything to Asar that doesn't use any new character is really tricky. This might not be as much of an issue if Asar used an AST or something similar, but with everything being the way it is and just kind of being all over the place, it's very difficult to use the same character for multiple purposes, even if it is in different contexts.

**Comment by p4plus2** [comment]
Merged with the current short hand of `<:` and a function built-in of `bank`.  I'll leave this open until 1.80 releases in case any objections crop up or somebody wishes to try a different syntax.

**Comment by p4plus2** [comment]
1.8 released, no need to leave this open.
