### ISSUE TITLE
implementation of a datasize function

### ISSUE THREAD

**Issue by p4plus2** [RPGHacker/asar#173]
I had a bit of an idea I just whipped up called `datasize`.  Basically it works similar to `sizeof` or `objectsize`, but on labels themselves.  It measures the the distance between a given label and the next label.  More testing is probably needed, especially around freespace.  But before I take it further, thoughts?

```
static int data_size(const char *name)
{
	unsigned int label;
	unsigned int next_label = 0xFFFFFF;
	if(!labels.exists(name)) asar_throw_error(1, error_type_block, error_id_label_not_found, name);
	label = labels.find(name) & 0xFFFFFF;
	labels.each([&next_label, label](const char *key, unsigned int current_label){
		current_label &= 0xFFFFFF;
		if(label < current_label && current_label < next_label){
			next_label = current_label;
		}
	});
	if(next_label == 0xFFFFFF) asar_throw_warning(1, warning_id_datasize_last_label, name);
	if(next_label-label > 0xFFFF) asar_throw_warning(1, warning_id_datasize_exceeds_size, name);
	return next_label-label;
}
```

(The above version is edited from the original to provide reasonable warnings, I've since wrote tests for the code with and without freespace and all seems to be working.  If there are no additional suggestions or tweaks to syntax I'll submit a PR)

**Comment by RPGHacker** [comment]
I'm just wondering what the use case for this would be. Isn't it the same as just doing, for example, something like this?
`lda next_label-current_label`
Or am I misunderstanding?

**Comment by p4plus2** [comment]
That is basically what it is.  But it has a few advantages:

1) If you move tables around, it'll automatically select the correct next_label
2) Less verbose code, while communicating what you really want
3) You don't need to add "end" labels all over or even need to know the next label name

Here is an example below from my homebrew:
```
prepare_oam:
	lda #DMA_settings(PPU.oam_write, !one_reg_once)
	sta DMA[3].settings
	stz DMA[3].source_bank
	lda #oam_mirror
	sta DMA[3].source_word
	lda #datasize(oam_mirror)	
	sta DMA[3].size
	
	lda !channel_3
	tsb dma_mirror
	rts
```

**Comment by RPGHacker** [comment]
I see, yeah, I do got the use case. My current stance on it is somewhat "mixed", because on one hand, I definitely see the convenience of it, and on the other hand it feels a bit too context-sensitive and too implicit for my liking.

That being said, it's only a function. Luckily functions can be added rather easily to Asar and are isolated enough from everything else to where they're harmless, so I wouldn't mind this addition at all. In other words, from me, it's an "okay".

In case you're going to implement this yourself via a PR, don't forget to also update the built-in functions section in the manual

**Comment by p4plus2** [comment]
Feature has been merged.
