### ISSUE TITLE
Proposed syntax and implementation of variadic macros

### ISSUE THREAD

**Issue by p4plus2** [RPGHacker/asar#178]
```
!a = 0
macro asd(...)
	db sizeof(...), <0>, <!a>
endmacro

macro sorry(...)
	!a = 0
	while !a < sizeof(...)
		db <!a>
		!a #= !a+1
	endif
endmacro

macro sorry2(asd, ...)
	!a = 0
	while !a < sizeof(...)
		db <!a>
		!a #= !a+1
	endif
	db <asd>
endmacro

%asd(1)
db $FF, $FF

%asd(1,2,3,4,5)
db $FF, $FF

%sorry(1,2,3,4,5,6,7)
db $FF, $FF
%sorry2(1,2,3,4,5,6,7)
```

Current caveat: Variadic macros will resolve defines (but traditional macros behave as they have in the past), This is important to allow iteration of variadic arguments. 
Implementation notes:

- Variadic args must be the last parameter
- Parameters must directly resolve to a number (no math `<1+2>` is invalid, defines with `#=` can work around for rare cases when this is useful)
- You may pass more args than you will actually use (but the converse, going out of bounds, is not allowed of course)
- You can use `sizeof(...)` to get the number of varargs

Current tests and implementation can be found in the experimental branch.

**Comment by RPGHacker** [comment]
Seems like a reasonable addition. At first I didn't quite understand how to access the varargs, but after checking the first example again, I get it now and it seems like the most reasonable implementation we could probably come up with. Using just the raw numbers as identifiers means that it likely won't conflict with anything (since I assume it isn't possible to use numbers as identifiers - that would be quite silly, after all).

So from me, it's a +1

**Comment by p4plus2** [comment]
> Using just the raw numbers as identifiers means that it likely won't conflict with anything (since I assume it isn't possible to use numbers as identifiers - that would be quite silly, after all).

Correct.  Normally that isn't possible, so this syntax choice shouldn't conflict with any existing patches.

**Comment by p4plus2** [comment]
Merged complete.
