### ISSUE TITLE
Macro comment wasn't documented?

### ISSUE THREAD

**Issue by GhbSmwc** [RPGHacker/asar#234]
I saw [this patch](https://www.smwcentral.net/?p=section&a=details&id=19222) on SMWC that fixes a bug with a couple of sprites "sometimes" interact with other sprites:
```
macro comment()
hi, this is my first patch lmao

Some sprites do not have any sprite interaction within their own code,
which means they ignore lower priority sprites that are loaded in.

so here we are

endmacro
```

Is this documented in the more recent version? I'm using version 1.81

**Comment by RPGHacker** [comment]
I'd say it's not documented because it isn't really a feature intentionally supported by Asar (and in fact, it's not guaranteed to keep working in future releases). It's something that just "happens to work", because the content of macros isn't evaluated until the respective macro is called.

That being said, this method does have its obvious limits that you will run into pretty quickly if you use it regularly. Since macro names have to be unique, you'd have to use a new name for every single comment you write this way. This would also raise the chance of clashing with another random macro somewhere. I'd say those things alone are enough reasons to not consider this an officially supported feature.

**Comment by randomdude999** [comment]
proper multiline comments are added in asar 2.0, the macros working well enough was just a happy accident i guess.
