### ISSUE TITLE
Continous Integration

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#36]
We could use it to automatically build release files (using Appveyor) and also to verify that pull requests don't break anything (probably using Travis, but i think Appveyor might work too and IMO it would be better to use only one).

**Comment by RPGHacker** [comment]
I'm planning to eventually add a WIP branch so that new changes can be added/merged while the master branch remains stable (especially since the master branch hosts the Asar website and commits to it will be immediately published to the online version of the manual).

Not sure about continous integration. I feel like right now, Asar progress is still small and slow enough to be perfectly manageable via pull requests and manual merges. Manual merges (as I have done them so far) pretty much assure that pull requests don't break anything - I usually make sure to review and test them locally before merging them into master. I feel like this is a pretty safe way of handling pull requests. As for making sure nothing breaks, that's what the test suite is intended for. Basically, when adding new features, it's a good idea to add a test to the tests folder (or edit an existing test) and make sure all tests still succeed in the test apps (that's what I've been doing with each pull request so far, I've added tests to v160features.asm where they were missing). Right now I feel quite comfortable doing everything by hand (although of course it's slower than automatic merges). Should it ever become too much, I will probably add some co-editors who can merge pull requests etc.

**Comment by randomdude999** [comment]
I actually didn't mean automatically merging pull requests, just that it would show a badge next to the pull request when it makes the test suite fail / doesn't compile. IMO it would help find some errors faster.

**Comment by RPGHacker** [comment]
I see, I'm not too familiar with this. Does GitHub support that out of the box?

**Comment by randomdude999** [comment]
If you manage to get it set up correctly, yes.

**Comment by RPGHacker** [comment]
Do you know what kind of format they expect to work? Just a command line application which returns a certain value or something like that? And do they not require a special build server or something like that?

**Comment by randomdude999** [comment]
They (appveyor or travis) provide the servers themselves. Also, you need a config file for them (that tells them how to build and test the app). The format they expect is quite configurable. I was thinking we could use Appveyor for artifact building (since it's windows based) and Travis CI for testing (since I've used that before, albeit only for python projects). You can also have Travis test against many different setups (different compilers, OS's, etc). Detecting whether tests were successful generally happens by checking whether the return code of the test program is non-zero, which is a good and simple system, and should be easy to adapt to asar's test application.

**Comment by randomdude999** [comment]
I've gotten asar to successfully build on Travis CI (https://github.com/randomdude999/asar/commits/ci-test) (a similar red cross/green check would be shown next to pull requests, signaling that the pull request build or doesn't). It looks like running the built-in test suite will be a bit complicated since it requires an unheadered SMW rom - putting it in any place where travis can access it is probably illegal.

**Comment by randomdude999** [comment]
OK, I got Appveyor to work too - https://ci.appveyor.com/project/randomdude99953139/asar. It even automatically exports the built EXE's and DLL's.

**Comment by randomdude999** [comment]
(also appveyor throws literally 220 warnings but not a single error)

**Comment by RPGHacker** [comment]
So right now it basically just acts like a build server, right?

**Comment by RPGHacker** [comment]
Also need to check out those warnings. I've been using VS2015 so far (because I don't have Visual Assist for VS2017 yet), but it seems like they changed quite a lot of stuff in the compiler to bump the warning count from 0 up to 220.

**Comment by RPGHacker** [comment]
Although I just realised that most of those warnings are actually from Windows header, ha. It still gets me every time.

**Comment by randomdude999** [comment]
I can actually configure it to use VS2015 if that gives less errors. Right now it just builds Asar, yeah.

**Comment by randomdude999** [comment]
Yup, with VS2015 it only has 8 warnings, all of which are in the windows headers.

**Comment by RPGHacker** [comment]
Nah, it's okay, I will take a look at those warnings later. I want to fix all warnings I see since often they exist for a good reason, and where there's nothing wrong I usually silence them via a pragma or similar. In fact, I'm pretty sure I have already done that and didn't get any warnings in my most recent VS2015 build, so I'm quite surprised about those 8 warnings, as well as the Windows warnings. Somehow the build server seems to use different settings than me or something like that. In any case I will check it out when I get the chance.

**Comment by randomdude999** [comment]
I've managed to switch the building into release mode (it generates smaller artifacts that way). Now it throws [209 warnings](https://ci.appveyor.com/project/randomdude99953139/asar/build/10/messages), most of which seem to be about automatic inline expansion. After disabling that warning (IMO it's not very helpful), there are only 8 remaining. All of them are about automatically converting parameter types in some windows headers, so I also disabled that warning. Now there are no warnings thrown (in appveyor, at least. Travis still has some i think).

**Comment by RPGHacker** [comment]
Don't quite get where they get their warnings from. Don't they just build your application in whatever environment you've set up and collect all the warnings and errors generated? So in other words, shouln't they get the same warnings we get when building in the same environment? (Admittedly I haven't built a Release build in quite a while, but I'm not sure where it would get additional conversion warnings from).

Anyways, I wouldn't disable the implicit conversion warning since it's actually quite a useful one to have and can help find some serious bugs in the code (have done so many times in the past). Automatic inline warning, on the other hand, I think we can safely disable. I don't think we ever need to care about that (unless maybe when looking to maximize performance, but even then probably not - I think an automatic inline really benefits performance more than it ever harms it).
