### ISSUE TITLE
Make test suite not require a clean SMW rom

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#39]
Currently running the built-in test suite requires having a clean unheadered SMW rom. This means that running the test suite in continous integration is AFAIK impossible to do legally (without sharing a ROM somewhere so the CI can access it). Currently only 11 tests need the clean SMW rom (`grep '^;@\+' tests/*.asm` too see which ones, mostly the ones dealing with freespace). We could replace this with a dummy ROM that is the same size as SMW but is completely garbage (it should include a few large blocks of nulls/0xFF's just to make sure the freespace finder doesn't find freespace in the original ROM space). Then we could include the dummy rom in the repo somewhere.

**Comment by RPGHacker** [comment]
A dummy ROM was also what I was thinking of. Though I don't think it even needs to contain garbage data. The freespace finder in Asar is already programmed to ignored banks < $10. What the dummy ROM does need, though, is the correct title, since one of the tests actually uses expecttitle. Might also need some other ROM settings for Asar to work correctly.

**Comment by randomdude999** [comment]
Okay, it looks like some of the tests actually verify the ROM checksum. They will then need to be updated too.
