### ISSUE TITLE
Asar does not parse untaken branches

### ISSUE THREAD

**Issue by Horrowind** [RPGHacker/asar#4]
The following assembles fine:
`if 0`
`complete bogus`
`endif`

In my opinion asar should raise an error here.

**Comment by RPGHacker** [comment]
I'd say it's the correct and expected behavior. C compilers also behave like this and it's a common method of quickly commenting out large blocks of code. I commonly see something like this being done in C code:

```
#if 0
void some_function_that_isnt_used_anymore()
{
    // ...
}
#endif
```

Parsing and validating code that definitely won't be compiled in that run would be unnecessary work done by Asar (and potentially a waste of performance if there was a lot of code in that block - for example, an incsrc or something like that).

**Comment by Horrowind** [comment]
Yeah, this seems to be right then. For some reason, my impression of the 'if' statement in asar was more that of a regular if statement in programming languages and not a preprocessor 'if'. But it seems that it decides statically if a branch is taken (considering that it excludes labels explicitly).

**Comment by RPGHacker** [comment]
Yeah, Asar lacks a lot of clarity in that regard. The if definitely functions more like a preprocessor if, but its implementation is a mess and doesn't even necessarily imply that. Implementing ifs and defines via actual preprocessors would have made Asar a lot cleaner, simpler and easier to understand.
