### ISSUE TITLE
Segfault when running asar with only options (no files)

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#42]
It won't work when passing invalid options, but passing only valid options will cause a segfault. For example, `asar --version`. This is because libcon_option assumes that there is at least one argument remaining after all optional arguments.

**Comment by randomdude999** [comment]
I fixed the segfault, but things are still acting a bit weird - since libcon_interactive gets disabled when there are any command line arguments, using only options will cause asar to be in non-interactive mode, effectively always printing the help text. But I guess it's still better than a segfault.

**Comment by RPGHacker** [comment]
What does "printing the help text" mean in this case? Does it just print Asar's usage? If so, I'd argue that that's actually the correct behavior here, because when you're passing just options and no input/output files to Asar, you're actually using it incorrectly, and when using it incorrectly, I'd say printing the usage is the most reasonable thing to do. Anyone who passes any command line arguments to Asar in the first place probably doesn't care about interactive mode in the first place, since interactive mode is really intended for people who can't (or don't want to) deal with command lines.
