### ISSUE TITLE
Useless files

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#51]
* Using Cmake, the [make.sh](https://github.com/RPGHacker/asar/blob/master/make.sh) in the root of the repo is unnecessary.
* I don't think you actually need the [_config.yml](https://github.com/RPGHacker/asar/blob/master/docs/_config.yml) in [docs/](https://github.com/RPGHacker/asar/tree/master/docs).
* [docs/shared/highlight_js/](https://github.com/RPGHacker/asar/tree/master/docs/shared/highlight_js) only needs [highlight.pack.js](https://github.com/RPGHacker/asar/blob/master/docs/shared/highlight_js/highlight.pack.js) and [styles/](https://github.com/RPGHacker/asar/tree/master/docs/shared/highlight_js/styles), the other files are unnecessary.
* I feel like [asar-dll-test](https://github.com/RPGHacker/asar/tree/master/src/asar-dll-test) and [asar-app-test](https://github.com/RPGHacker/asar/tree/master/src/asar-app-test) could be merged with [asar-tests-shared](https://github.com/RPGHacker/asar/tree/master/src/asar-tests-shared), kinda like asar-standalone and asar are merged

**Comment by RPGHacker** [comment]
I think _config.yml is a file auto-generated by GitHub. I don't know what would happen if we removed it, so I'd rather keep it. I also wouldn't remove the LICENSE file from highlight_js, it's safer to keep it (and probably legally required).

I don't quite remember why I decided to split the test applications like that. Maybe so that you can build one without having to build the other? That doesn't explain why I didn't split Asar DLL and Asar executable in the same way, though. It's been quite a while since I did that.

I agree on all the other files, though, they should be safe to delete.

**Comment by randomdude999** [comment]
I think you only need Github Pages' _config.yml when using Jekyll or similar. All of my GH Pages repos work without it.

**Comment by randomdude999** [comment]
Should I also try to merge the two test suites?

**Comment by RPGHacker** [comment]
You can give it a try. If you do, make sure that there is a way for the user to decide what tests they want to build (both tests, just one test or no test at all). I assume something like what boldowa did with the CMake options would be ideal here.
