### ISSUE TITLE
Double to unsigned int conversion error

### ISSUE THREAD

**Issue by Horrowind** [RPGHacker/asar#57]
The following code gives unintuitive results. 

```
print hex($7FFFFFFF)
print hex($FFFFFFFF)
```
gives
```
7FFFFFFF
80000000
```
In `assembleblock.cpp` we convert to `unsigned int` and call `hex0`, which in turn also expects an `unsigned int`. So I have no idea where this comes from.

From my observations, this should be the equivalent C code, which gives the correct result:
```
#include <stdio.h>
int main() {
    double f = 0xFFFFFFFF;
    printf("%X\n", (unsigned int)f);
    return 0;
};
```

**Comment by RPGHacker** [comment]
Huh, don't get this, either. I thought I already fixed this bug in Asar 1.40 (see changelog), but guess it's yet another one of those? Or maybe it only happens on certain platforms...

**Comment by randomdude999** [comment]
On my 32-bit windows and 64-bit linux, it gives `7FFFFFFF` and `80000000`, but on my raspberry pi (not sure how many bits it is, it's ARMv6) it gives `7FFFFFFF` for both of them...
It also happens when doing `dd`, so it probably isn't related to the print.

**Comment by randomdude999** [comment]
For `dd` at least, the culprit is line 1171 of assembleblock.cpp (which declares `num` as `int`). Actually, main.cpp:240, `getnum` returns an `int` but it should return an `unsigned int`. This could be fixed by removing the `int` cast from the return (main.cpp:251), changing the function prototype to return `unsigned int` and then changing every place where `getnum` is used.
