### ISSUE TITLE
Proposal: Remove xkas support.

### ISSUE THREAD

**Issue by Horrowind** [RPGHacker/asar#6]
From the manual:
> New features introduced into Asar since then might not throw warnings when attempted to use in xkas compatibility mode and old xkas patches might not assemble correctly with Asar anymore, even when xkas compatibility mode is used.

Maybe we should remove xkas support altogether? (Probably after a community discussion?)

**Comment by RPGHacker** [comment]
It's something that has certainly crossed my mind before. Currently, my thoughts on this matter are this: Removing xkas support should be possible, but would take a bit of time since some aspects of it are deeply woven into Asar. That aside, I'm not quite sure if there were some actual considerable benefits from removing it. The code would probably get a bit cleaner, but even without xkas support I think it would remain messy enough to probably not be worth the effort. On the other hand, since xkas support isn't actively maintained anymore, I don't think it currently does any harm by being there. Additionally, there might still be a few unconverted xkas resource available somewhere out there which some person might appreciate being able to use.

So right now, I'm not sure if there would be much to gain from removing xkas support. If I were to code a new Asar from scratch, I certainly wouldn't care much about xkas support and leave it out to keep code cleaner and simpler, but for the current version, I don't think there are quite enough benefits from removal.

**Comment by Horrowind** [comment]
I just tested it. Removing xkas support is not that difficult actually. I removed all the occurrences of the emulatexkas and warnxkas (and the bit of code which set both of them).

If you want I can send a pull request. It is completely untested now, but I would test this, if you are okay with a PR. Anyway: Removed code is the best code.

**Comment by RPGHacker** [comment]
That answers that part, it seems.

Still hestitant on actually merging it, though, since as mentioned before, there might remain the rare, overlooked xkas resource somewhere that some people might want to use. I suppose if it's something with notable benefits, it's worth discussing in the community before deciding to remove it or to keep it.

**Comment by RPGHacker** [comment]
It's currently being discussed in the staff forum. So far, a number of people seem to support it, but not many have voted yet, so it's note quite enough to make a decission yet. Will update this once a decision can be made.

**Comment by RPGHacker** [comment]
(Reopening, just so that we don't forget to actually remove xkas support in a future version - deprecation warnings are already in place now, though)

**Comment by RPGHacker** [comment]
(Just posting this here as a reminder to myself)
autoclear and freespace fixed also throw deprecation warnings now and should be removed whenever xkas support is removed.

**Comment by p4plus2** [comment]
- [ ] $000000,y -> $0000,y
- [ ] jmp $000000 -> jml $000000
- [ ] # as a number prefix (getnum)
- [ ] xkas command (which is just the enabler)
- [ ] asar is 1 byte less strict with warnpc
- [ ] xkas rep trick
- [ ] incbin/src path hack (doesn't the vfs handle this now anyways?)
- [ ] dequoting defines

List of all currently emulated xkas features, honestly I don't see a reason to support most of these anymore.  Does anybody have evidence to the contrary? All are locked behind the xkas emulation flag.

**Comment by RPGHacker** [comment]
I don't have any concrete data on how common (or uncommon) any of those are. One of the main reasons why I added deprecation warnings to most of the xkas features I was aware of in a prior version.

**Comment by p4plus2** [comment]
All xkas features are deprecated in 1.9 and removed in 2.0 making this completed.
