### ISSUE TITLE
tests/bankcross.asm is too big

### ISSUE THREAD

**Issue by randomdude999** [RPGHacker/asar#93]
https://github.com/RPGHacker/asar/blob/1ee9ef4810b097ca788ddbe8babd9e2f0c587710/tests/bankcross.asm#L660-L661

For these 2 lines, the test checks every byte in the range $068002-$078000 (lines 37-548 in that file). It should probably only check the first and last bytes.

**Comment by RPGHacker** [comment]
Don't think it currently can. I think the test suite always mem-compares the entire output ROM with the entire expected ROM, and since the expected ROM is 0-initialized, I think it would throw mismatches here, because it would expect 0, but get 42.

In other words: the test application will have to be rewritten to make this work. It could be rewritten to only check all of the stuff that is actually specified in a test. Would just take a bit of effor to do that. We would have to use a dynamic list of some kind. Probably something like `std::map<int32_t, std::vector<uint8_t> >`, where the int32_t stored a position in ROM and the vector stored the bytes expected at that position. Would also need a new parameter for our tests to specify a ROM's expected size (either that, or we ignore size mismatches entirely).

**Comment by randomdude999** [comment]
Never mind, it looks like the ROM checksum has a special edge case. I think we could fix this by instead of using NULLs as the expected ROM by default it would use the ROM generated by applying the patch, then write all the expected bytes there, and then compare it with the patch ROM.

(It might sound confusing, but basically, set `expectedrom` to `truerom` before adding the test bytes from the test file)

For this test though, I think we don't even have to pad the entire bank, just padding the last few bytes of the bank should be enough, right?

**Comment by RPGHacker** [comment]
You're right, that sounds like the simpler solution. Basically, we move the part where it reads the header of the .asm files to the end of the test.

And yeah, you're probably right. Not quite sure why I decided to pad that much. Maybe because I was trying to faithfully reproduce the scenario that Ladida was mentioning in the bug report back then? We can now reduce it to just a couple of bytes, though.
